### ISSUE TITLE
ProgressBar Aria Label

### ISSUE THREAD

**Issue by zrothberg** [Brain-Bones/skeleton#312]
So looking at the mozilla docs for the [meter label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/meter_role). It appears as though they are suggesting against using the aria label outright. And to use the HTML tag. Further I am unsure if the aria label should be meter vs progressbar. Meter doesnt support indeterminate values [while progressbar does. ](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role) 

Was there a specific reason for switching from the native HTML tag to the custom one via aria roles? The original commit doesnt say why just that it was happening.

**Comment by endigo9740** [comment]
Hi @zrothberg we always welcome a11y improvements so thanks for providing this!

I'm a BIG advocate of leaning into native elements over custom anytime possible. It's been many months since we built this one specifically, but I believe we opted for this route given it was difficult to create the indeterminate animations as we wanted. Likewise I seem to recall some issues with consistent styling across browsers/OS for the element iself.

In hindsight I can imagine some ways we might could deal with this in a better fashion. Now that we have a few new features and techniques established in the project, if I was to build this today I might do the following:

Option 1:
Use our Tailwind Elements (essentially just CSS styles) to customize the native element, assuming browsers play nice

Option 2:
Keep it a component, but dynamically switch between the native progress bar when a value is present, and an HTML fallback with animations when no value is available.

Perhaps we make this ticket a feature request to revisit this one? Likewise I'd welcome a PR if someone like yourself wanted to take this one.

**Comment by zrothberg** [comment]
@endigo9740 I wonder if the inconsistencies is because of default style sheets. I don't think tailwind defaults to clearing the styles for html5 tags only the baseline ones. Just peaking chrome vs safari on OSX I see that chrome has some stuff marked as important by default while safari does not. You may need to make an expanded preflight section that clears the default styles for html5 tags you want to use. I can take a stab at getting them to play nicely. Do you happen to know which os/browsers where having issues? Happy to check several out but I don't have a windows computer to check that environment set. 

I think another option outside of the 2 you mentioned would be maybe take some stuff and transform them to a preprocessor. I think for a few semi-primitives that don't have actual behavior but are just injecting a small amount of pre styled css plus a few other things it may be better to use a custom svelte (tag? not sure what its called) and modify the code before svelte compiles it. That has a further advantage of allowing the user to control how primitive components would render by default inside skeleton. It would also be useful for something complex like a form where you may want to actually inspect the injected markup and fill in some stuff like aria labels and ids without the user needing to write them. 

[Here is a lib that does it ](https://github.com/l-portet/svelte-switch-case) for switch case tags but I can't imagine its THAT difficult to modify the approach to inject some html. Though I may be underestimating that.

**Comment by endigo9740** [comment]
@zrothberg Just saw your new message so I'll respond to that in a moment, but wanted to share what I'm seeing when cross browser testing CSS styles for the progress element.

Here's the styles tested:
```css
progress:not([value]) {
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
	border: none;
	width: 100%;
	height: 10px;
}
progress[value] {
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
	border: none;
	width: 100%;
	height: 10px;
}

/* Indeterminate */
:indeterminate::-webkit-progress-bar {
	width: 100%;
}

/* Bar */
progress::-webkit-progress-bar {
	background-color: #eee;
	border-radius: 2px;
}
progress::-moz-progress-bar {
	background-color: #eee;
	border-radius: 2px;
}

/* Value */
progress::-webkit-progress-value {
	background-color: red;
	border-radius: 2px;
}
progress::-moz-progress-value {
	background-color: red;
	border-radius: 2px;
}
```

Here's the results...

Chrome: 
![chrome](https://user-images.githubusercontent.com/1509726/193146981-b3b28f65-6c02-4108-9fcf-b40b48b3bfad.png)

Safari:
![safari](https://user-images.githubusercontent.com/1509726/193146983-3a7bbf42-38fe-46bb-ad79-33b71ba2ff7d.png)

Firefox:
![firefox](https://user-images.githubusercontent.com/1509726/193146984-c8782d1a-53b9-42f4-a8f8-ab01fcbf5554.png)

As you can see, Chrome and Safari render fairly similar, which is not surprising given their shared lineage. But Firefox doesn't show the value at all. I have no idea why.

I'm following the instructions per the following resources:

- https://css-tricks.com/html5-progress-element/
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress
- https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-progress-bar

Notable `-moz-progress-value` doesn't seem to exist, which is part of my confusion here.

But in short, you can see how many crazy vendor properties are needed to style this element! It's a bit nuts!

**Comment by endigo9740** [comment]
FYI I also tested accent color, which MDN claims is supported. But I'm not sure how to properly utilize it:

```css
progress {
	accent-color: red;
}
```

This doesn't appear to affect the three browsers tested above. I get the same default styles. I also tested with the vendor appearance set to none, and setting this on the body element.
